# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
