# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-18 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_remove_trainer_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='trainer_profile',
            field=models.FileField(upload_to=''),
        ),
    ]
