# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-21 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_auto_20170718_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='technology',
            field=models.CharField(max_length=250),
        ),
    ]
