# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-24 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_curriculum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curriculum',
        ),
    ]
