# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_trainer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='contact',
            field=models.CharField(default='+91', max_length=20),
        ),
    ]
