# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_trainer_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Technology', models.CharField(max_length=100)),
            ],
        ),
    ]
