# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0012_auto_20170801_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='contact',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='technology',
            new_name='Technology',
        ),
    ]
