# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0013_auto_20170801_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Technology',
            new_name='technology',
        ),
    ]
