# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-01 10:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0014_auto_20170801_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name=datetime.date(2017, 8, 1))),
                ('certificateId', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
