# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-01 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0015_auto_20170801_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificateId',
            field=models.CharField(default='Skill / 18050123 / ', max_length=50),
        ),
    ]
