# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-02 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0016_auto_20170801_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='sheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.date(2017, 8, 2)),
        ),
    ]
