# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-02 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0018_auto_20170802_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
